var tweets = [
  { id: 1,
    text: "We can neither confirm nor deny that this is our first tweet.",
    author: "CIA",
    timeStamp: new Date(2014, 2, 3, 7, 6, 5),
    shown: false},
  { id: 2,
    text: "Pacific Ocean is about 15x larger than US & covers about 28% of Earth's surface #WorldFactbook http://1.usa.gov/1vbyvRt",
    author: "CIA",
    timeStamp: new Date(2014, 2, 3, 4, 5, 6),
    shown: false},
  { id: 3,
    text: "#Intrepid played key role in vision that established COI, OSS & CIA, he helped revolutionize US intel capabilities http://1.usa.gov/1EKjbUm",
    author: "CIA",
    timeStamp: new Date(2014, 1, 2, 3, 4, 5),
    shown: false},
  { id: 4,
    text: "Dulles put his aides to work on the #panda problem; his assistant was soon nicknamed “the Vice President of Pandas” by his colleagues.",
    author: "CIA",
    timeStamp: new Date(2014, 0, 1, 2, 3, 4),
    shown: false},
];
